default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: example
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: area_mais_development

test:
  <<: *default
  database: area_mais_test

production:
  primary: &primary_production
    <<: *default
    database: area_mais_production
    username: area_mais
    password: <%= ENV["AREA_MAIS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: area_mais_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: area_mais_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: area_mais_production_cable
    migrations_paths: db/cable_migrate
